'use strict';
const SYSTEMS=[['chassis','Châssis','Structure',250,260,70,205],['ia','IA','Structure',250,117,421,109],['direction','Direction','Commandes',250,208,420,184],['pedalier','Pédalier','Commandes',250,168,70,146],['chaise','Chaise / siège','Habitacle',250,284,420,278],['firewall','Firewall','Sécurité',250,333,70,330],['suspension-avant','Suspension train avant','Trains roulants',172,171,70,95],['train-arriere','Train arrière','Trains roulants',166,405,70,437],['tsac','TSAC','Énergie',250,371,420,356],['punch-bar','Punch bar','Structure',250,437,420,449],['aileron-avant','Aileron avant','Aérodynamique',250,63,70,39],['aileron-arriere','Aileron arrière','Aérodynamique',250,480,420,498],['carrosserie','Carrosserie','Aérodynamique',217,230,70,263],['fond-plat','Fond plat','Aérodynamique',179,342,70,383],['side-pod','Side pod','Aérodynamique',322,320,420,317],['fixation-chassis','Fixation châssis','Structure',289,395,420,401],['ses','SES','Dossier transversal'],['ases','ASES','Dossier transversal'],['boom','BOOM','Dossier transversal']];
// Les systèmes correspondent à la liste du projet ; TSAC et punch bar ont chacun leur fiche.
const STAGES=['Conception','Plan','Fabrication','Montage','Test'];
const $=s=>document.querySelector(s), empty=()=>({steps:[0,0,0,0,0],deadline:'',owner:'',problems:'',solutions:'',notes:'',revision:0,updatedAt:''});
let records={},selected=null,draft=null,dirty=false,connected=false,token='',saving=false;
try{token=sessionStorage.getItem('vrt-team-token')||'';}catch{}
const API=window.VRT_API||new URL('./api/',location.href).href.replace(/\/$/,'');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function status(r){return r.steps.every(s=>s===2)?'done':r.steps.some(s=>s>0)?'active':'empty';}
function late(r){return r.deadline&&r.deadline<localDate()&&status(r)!=='done';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),6000);}
function car(){const tires=[[127,143],[335,143],[127,382],[335,382]].map(([x,y])=>`<rect x="${x}" y="${y}" width="38" height="74" rx="12" fill="#222227"/><path d="M${x+8} ${y+6}v62m22-62v62" stroke="#49494e" stroke-width="2"/>`).join('');
$('#car-stage').innerHTML=`<svg viewBox="0 0 500 540" xmlns="http://www.w3.org/2000/svg" role="group" aria-label="Voiture VRT, sélection interactive des systèmes"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#ddddE3"/></pattern><linearGradient id="body" x1="0" x2="1"><stop stop-color="#bdbdc6"/><stop offset=".48" stop-color="#f7f7fa"/><stop offset="1" stop-color="#ceced8"/></linearGradient></defs><rect width="500" height="540" fill="url(#grid)"/><path d="M250 24v494" stroke="#cacad1" stroke-dasharray="5 6"/><text x="250" y="20" text-anchor="middle" font-size="8" letter-spacing="3" fill="#9999a2">AVANT ↑</text><g stroke="#787881" stroke-width="2" fill="none"><path d="M149 177l89-42m-89 42l79 43m126-43l-90-42m90 42l-81 43M147 410l67-40m-67 40l78 29m127-29l-68-40m68 40l-79 29"/><path d="M150 177h201M147 412h205" stroke-width="5"/></g>${tires}<path d="M195 186Q250 148 305 186L330 378 302 438H199l-30-60z" fill="#e1e1e6" stroke="#9c9ca5"/><path d="M223 78h54l10 99 20 43-13 187h-88l-13-187 21-43z" fill="url(#body)" stroke="#808089" stroke-width="2"/><path d="M180 251l26-15-2 136-22 20-15-63zM320 251l-26-15 2 136 22 20 15-63z" fill="#d70920" stroke="#980b1c"/><path d="M228 218q22-23 44 0l10 76q-32 29-64 0z" fill="#24242a" stroke="#696975" stroke-width="3"/><path d="M229 245q21-13 42 0l-5 48h-33z" fill="#45454f"/><ellipse cx="250" cy="220" rx="21" ry="9" fill="none" stroke="#dbdbe2" stroke-width="5"/><rect x="218" y="340" width="64" height="56" rx="6" fill="#777780" stroke="#454550" stroke-width="2"/><path d="M226 350h48m-48 9h48m-48 9h48m-48 9h48" stroke="#aaaab4"/><path d="M210 327h81" stroke="#34343d" stroke-width="7"/><path d="M221 122l28-28 29 28m-63 42h70m-86 242l94-70m-92 0l94 70" stroke="#666671" fill="none" stroke-width="3"/><g fill="#d70920" stroke="#a60719"><path d="M153 49q97 13 194 0v30q-97-11-194 0z"/><path d="M155 468h190v30H155z"/></g><path d="M164 60h172M166 480h168" stroke="#ffffff" stroke-width="4"/><image href="vrt-logo.svg" x="230" y="134" width="40" height="16" transform="rotate(-90 250 142)"/>${SYSTEMS.map((s,i)=>s.length>3?`<g class="hotspot" data-id="${s[0]}" tabindex="0" role="button" aria-label="${esc(s[1])}"><title>${esc(s[1])}</title><line x1="${s[3]}" y1="${s[4]}" x2="${s[5]}" y2="${s[6]}"/><circle cx="${s[5]}" cy="${s[6]}" r="17"/><text x="${s[5]}" y="${s[6]+3}" text-anchor="middle">${String(i+1).padStart(2,'0')}</text></g>`:'').join('')}</svg>`;
document.querySelectorAll('.hotspot').forEach(el=>{el.onclick=()=>openDetail(el.dataset.id);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(el.dataset.id);}};});}
function render(){const q=$('#search').value.toLocaleLowerCase('fr'),filter=$('#filter').value;let completed=0;SYSTEMS.forEach(s=>{const r=records[s[0]]||empty();completed+=r.steps.filter(x=>x===2).length;const el=document.querySelector(`.hotspot[data-id="${s[0]}"]`);if(el)el.dataset.state=status(r);});$('#total-progress').innerHTML=connected?`${Math.round(completed/(SYSTEMS.length*5)*100)}<span>%</span>`:'—';$('#completed-count').textContent=connected?`${completed} / ${SYSTEMS.length*5} étapes terminées`:'Connexion à l’espace équipe requise';
const rows=SYSTEMS.map((s,i)=>({s,i,r:records[s[0]]||empty()})).filter(({s,r})=>s[1].toLocaleLowerCase('fr').includes(q)&&(filter==='all'||(connected&&(filter==='late'?late(r):status(r)===filter))));$('#system-list').innerHTML=rows.length?rows.map(({s,i,r})=>{let state=status(r),label=!connected?'Ouvrir la fiche':late(r)?'En retard':{done:'Terminé',active:'En cours',empty:'À démarrer'}[state];return `<button class="system-row" data-id="${s[0]}"><span class="system-number">${String(i+1).padStart(2,'0')}</span><span class="system-info"><span class="system-name">${esc(s[1])}</span><span class="system-meta">${esc(s[2])}${connected&&r.deadline?' · '+new Intl.DateTimeFormat('fr-CH').format(new Date(r.deadline+'T12:00:00')):''}</span><span class="mini-progress">${r.steps.map(v=>`<i class="${v===2?'done':v===1?'active':''}"></i>`).join('')}</span></span><span class="row-status ${connected?(late(r)?'late':state):''}">${label}</span><span class="arrow">↗</span></button>`;}).join(''):'<p class="empty">Aucun système ne correspond à ce filtre.</p>';document.querySelectorAll('.system-row').forEach(el=>el.onclick=()=>openDetail(el.dataset.id));}
function renderSteps(){$('#steps').innerHTML=STAGES.map((s,i)=>`<button type="button" class="step" data-step="${i}" data-state="${draft.steps[i]}" aria-label="${s} : ${['à démarrer','en cours','terminé'][draft.steps[i]]}. Cliquer pour changer."><span>${draft.steps[i]===2?'✓':String(i+1).padStart(2,'0')}</span>${s}<small>${['À démarrer','En cours','Terminé'][draft.steps[i]]}</small></button>`).join('');document.querySelectorAll('.step').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.step);draft.steps[i]=(draft.steps[i]+1)%3;dirty=true;renderSteps();});}
function openDetail(id){if(!connected){showConnect();return;}if(dirty)return;selected=id;const s=SYSTEMS.find(s=>s[0]===id);draft=structuredClone(records[id]||empty());dirty=false;$('#conflict-warning')?.remove();$('#detail-title').textContent=s[1];$('#detail-category').textContent=s[2]+' / FICHE SYSTÈME';for(const key of ['deadline','owner','problems','solutions','notes'])$('#detail-form').elements[key].value=draft[key];$('#saved-at').textContent=draft.updatedAt?'Dernier enregistrement : '+new Date(draft.updatedAt).toLocaleString('fr-CH'):'Aucune modification enregistrée';renderSteps();$('#detail').showModal();}
function closeDetail(){if(saving)return;if(!dirty||confirm('Fermer sans enregistrer les modifications de cette fiche ?')){$('#detail').close();dirty=false;}}
async function request(path,options={}){const response=await fetch(API+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});let data;try{data=await response.json();}catch{throw new Error('Le service partagé n’est pas encore disponible.');}if(!response.ok){const error=new Error(data.error||'Impossible de contacter le service partagé.');error.status=response.status;throw error;}return data;}
async function refresh(){const data=await request('/systems');records=data.records;connected=true;render();$('#storage-label').textContent='Synchronisé avec l’équipe · '+new Date().toLocaleTimeString('fr-CH',{hour:'2-digit',minute:'2-digit'});}
function showConnect(){$('#connect').showModal();}
function connectUI(){const dialog=document.createElement('dialog');dialog.id='connect';dialog.innerHTML='<form id="connect-form"><div class="dialog-top"><p class="eyebrow">ESPACE ÉQUIPE VRT</p><button class="close" type="button" aria-label="Fermer">×</button></div><img class="login-logo" src="vrt-logo.svg" alt="VRT"><h2>Construisons ensemble.</h2><p class="dialog-sub">Entre le code d’accès de l’équipe pour retrouver le même suivi sur tous tes appareils.</p><label>Code d’accès<input type="password" name="code" autocomplete="current-password" required></label><p id="connect-error" role="alert"></p><button class="primary" type="submit">Rejoindre l’atelier ↗</button><p class="dialog-sub">Le code reste dans cet onglet jusqu’à la déconnexion.</p></form>';document.body.append(dialog);dialog.querySelector('.close').onclick=()=>dialog.close();$('#connect-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;token=e.target.elements.code.value.trim();try{await refresh();try{sessionStorage.setItem('vrt-team-token',token);}catch{}dialog.close();e.target.reset();toast('Bienvenue dans l’atelier partagé.');}catch(error){connected=false;token='';$('#connect-error').textContent=error.message;}finally{button.disabled=false;}};const button=document.createElement('button');button.className='quiet';button.id='connection';button.textContent='Équipe';button.onclick=()=>{if(connected){if(!confirm('Déconnecter cet appareil de l’espace équipe ?'))return;if(dirty&&!confirm('Une fiche contient des modifications non enregistrées. Les abandonner ?'))return;token='';try{sessionStorage.removeItem('vrt-team-token');}catch{}records={};connected=false;dirty=false;$('#detail').close();render();$('#storage-label').textContent='Déconnecté de l’espace équipe';}showConnect();};$('.header-right').append(button);}
$('#detail-form').oninput=()=>{dirty=true;};$('#close').onclick=closeDetail;$('#detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});$('#detail-form').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;const button=e.target.querySelector('[type=submit]');button.disabled=true;button.textContent='Enregistrement…';for(const key of ['deadline','owner','problems','solutions','notes'])draft[key]=e.target.elements[key].value;try{const data=await request('/systems/'+selected,{method:'PUT',body:JSON.stringify(draft)});records[selected]=data.record;dirty=false;$('#detail').close();render();toast('Fiche enregistrée pour toute l’équipe.');}catch(error){toast(error.message);if(error.status===409){const warning=document.createElement('p');warning.textContent='Une autre personne a modifié cette fiche. Copie tes notes avant de fermer puis rouvre la fiche pour retrouver la dernière version.';warning.setAttribute('role','alert');if(!$('#conflict-warning')){warning.id='conflict-warning';$('#saved-at').after(warning);}await refresh().catch(()=>{});}}finally{saving=false;button.disabled=false;button.textContent='Enregistrer la fiche ↗';}};
$('#search').oninput=render;$('#filter').onchange=render;
$('#export').onclick=async()=>{if(!connected){showConnect();return;}try{await refresh();const url=URL.createObjectURL(new Blob([JSON.stringify({format:'vrt-mec',version:1,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='VRT-mec-'+localDate()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Sauvegarde exportée.');}catch(error){toast(error.message);}};
$('#import').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(!connected){showConnect();return;}try{if(file.size>2000000)throw new Error('Le fichier est trop volumineux.');const data=JSON.parse(await file.text());if(data.format!=='vrt-mec'||data.version!==1||!data.records||typeof data.records!=='object'||Array.isArray(data.records))throw new Error('Ce fichier n’est pas une sauvegarde VRT valide.');if(!confirm('Importer cette sauvegarde remplacera les fiches correspondantes pour toute l’équipe. Continuer ?'))return;await refresh();const updates=Object.entries(data.records).map(([id,r])=>({...r,id,revision:records[id]?.revision||0}));await request('/import',{method:'POST',body:JSON.stringify({updates})});await refresh();toast('Sauvegarde importée pour toute l’équipe.');}catch(error){toast(error.message||'Sauvegarde invalide.');}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
car();connectUI();render();$('#storage-label').textContent='Espace partagé · Connecte-toi pour charger le suivi';
if(token)refresh().catch(error=>{connected=false;render();$('#storage-label').textContent=error.message;});
setInterval(()=>{if(connected&&!document.hidden)refresh().catch(()=>{$('#storage-label').textContent='Connexion interrompue · Tes modifications ouvertes sont conservées';});},15000);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_vrt_system',description:'Ouvre la fiche d’un système VRT sans la modifier.',inputSchema:{type:'object',properties:{id:{type:'string',enum:SYSTEMS.map(s=>s[0])}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({id})=>{if(!SYSTEMS.some(s=>s[0]===id))throw new Error('Système inconnu');if(dirty)throw new Error('Enregistrer ou fermer la fiche actuelle avant de continuer');openDetail(id);return {opened:connected? id:'connection'};}})).catch(()=>{});}catch{}}
