import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile,readdir} from 'node:fs/promises';
import {handle} from './worker.mjs';
import {adapter} from './dev.mjs';
async function setup(){const db=new DatabaseSync(':memory:');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')))db.exec(await readFile('drizzle/'+f,'utf8'));const env={DB:adapter(db),TEAM_CODE:'test-access'};return {db,async call(path,method='GET',body,code='test-access',origin){const headers={Authorization:'Bearer '+code};if(origin)headers.Origin=origin;const r=await handle(new Request('https://vrt.test/api/'+path,{method,headers,body:body?JSON.stringify(body):undefined}),env);return {status:r.status,body:await r.json(),headers:r.headers};}};}
const record=(revision=0)=>({steps:[2,1,0,0,0],deadline:'2026-10-02',owner:'VRT',problems:'Jeu dans la fixation',solutions:'Revoir la tolérance',notes:'À valider',revision});
test('code obligatoire, tentatives limitées et CORS',async()=>{const s=await setup();assert.equal((await s.call('systems','GET',null,'incorrect')).status,401);assert.equal((await s.call('systems')).status,200);assert.equal((await s.call('systems','GET',null,'test-access','https://evil.example')).status,403);assert.equal((await s.call('systems','GET',null,'test-access','https://gillesmariethoz.github.io')).headers.get('Access-Control-Allow-Origin'),'https://gillesmariethoz.github.io');for(let i=0;i<8;i++)assert.equal((await s.call('systems','GET',null,'incorrect')).status,401);assert.equal((await s.call('systems','GET',null,'incorrect')).status,429);s.db.close();});
test('sauvegarde partagée et conflit de deux éditeurs',async()=>{const s=await setup();assert.deepEqual((await s.call('systems')).body.records,{});const first=await s.call('systems/chassis','PUT',record());assert.equal(first.status,200);assert.equal(first.body.record.revision,1);assert.equal((await s.call('systems')).body.records.chassis.problems,'Jeu dans la fixation');const conflict=await s.call('systems/chassis','PUT',{...record(),notes:'Écrasement'});assert.equal(conflict.status,409);assert.equal((await s.call('systems')).body.records.chassis.notes,'À valider');assert.equal((await s.call('systems/chassis','PUT',record(1))).status,200);s.db.close();});
test('import atomique, validation et conservation des autres systèmes',async()=>{const s=await setup();await s.call('systems/chassis','PUT',record());let imp=await s.call('import','POST',{updates:[{id:'chassis',...record(0)},{id:'ia',...record()}]});assert.equal(imp.status,409);assert.equal((await s.call('systems')).body.records.ia,undefined);imp=await s.call('import','POST',{updates:[{id:'chassis',...record(1)},{id:'ia',...record()}]});assert.equal(imp.status,200);assert.equal(Object.keys((await s.call('systems')).body.records).length,2);assert.equal((await s.call('systems/inconnu','PUT',record())).status,400);assert.equal((await s.call('systems/ia','PUT',{...record(1),deadline:'2026-02-30'})).status,400);assert.equal((await s.call('systems/ia','PUT',{...record(1),steps:[3,0,0,0,0]})).status,400);assert.equal((await s.call('import','POST',{updates:[{id:'ia',...record(1)},{id:'ia',...record(1)}]})).status,400);s.db.close();});
